### ISSUE TITLE
Create functionality to share articles via email

### ISSUE THREAD

**Issue by kevinbowen777** [kevinbowen777/news#262]

**Comment by priddhesh** [comment]
Assign me this task I have worked on same issue before.

**Comment by kevinbowen777** [comment]
> Assign me this task I have worked on same issue before.

While I appreciate the interest & enthusiasm, I've got it handled. Thank you.

**Comment by priddhesh** [comment]
@kevinbowen777 Can you please assign me the issues that are still open?

**Comment by kevinbowen777** [comment]
> @kevinbowen777 Can you please assign me the issues that are still open?

No thank you. I am working of them myself. Have a good day.
